# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SpatialDBKitExample' do
  pod 'SpatialDBKit', :path => '../'
end

target 'SpatialDBKitExampleTests' do

end

